version: '3'

volumes:
  brmed_local_postgres_data: {}
  brmed_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: brmed_local_django
    container_name: brmed_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: brmed_production_postgres
    container_name: brmed_local_postgres
    volumes:
      - brmed_local_postgres_data:/var/lib/postgresql/data
      - brmed_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"
