# Generated by Django 4.0.9 on 2023-02-13 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('quote_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quote BRL')),
                ('quote_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quote EUR')),
                ('quote_jpy', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Quote JPY')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='response')),
                ('status_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='status code')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
