# Generated by Django 4.0.9 on 2023-02-13 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highcharts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='user',
        ),
    ]
